services:
  - type: web
    name: backend
    env: node
    buildCommand: "cd chess-online && npm install"
    startCommand: "cd chess-online && npm start"
   
  - type: web
    name: frontend
    env: node
    buildCommand: "cd Chess && npm install && npm run build"
    startCommand: "cd Chess && npm run start"
