services:
  - type: static
    name: chess-frontend
    buildCommand: cd Chess && npm install && npm run build
    publishDir: Chess/dist
    envVars:
      - key: NODE_ENV
        value: production

services:
  - type: web
    name: chess-backend
    env: node
    buildCommand: cd chess-online && npm install
    startCommand: node chess-online/server.js
    envVars:
      - key: NODE_ENV
        value: production
